# Generated by Django 5.2.10 on 2026-01-13 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_practicequestion_section_jobdescription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='attempted',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='correct',
            new_name='total_questions',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='section',
        ),
        migrations.AddField(
            model_name='progress',
            name='accuracy',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progress',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
