# Generated by Django 5.2.9 on 2026-02-09 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_rename_attempted_progress_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.section'),
        ),
    ]
