# Generated by Django 5.2.10 on 2026-03-01 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_interviewattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('constraints', models.TextField(blank=True)),
                ('initial_code', models.TextField(default='def solution():\n    pass')),
                ('test_cases_json', models.TextField(help_text="JSON list of test case dicts [{'input': '...', 'expected': '...'}]")),
                ('tag', models.CharField(default='Algorithms', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CodingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=5)),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('tags_breakdown_json', models.TextField(default='{}')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
